#!/usr/bin/env node
/**
 * Copies forge `out/<Contract>.sol/<Contract>.json` ABIs into packages/contracts/src/abis.
 * Also exports creation bytecode for browser-deployable adapters (FeeSplitter, PushAdapter).
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "../../..");
const outDir = join(root, "out");
const abiDir = join(root, "packages/contracts/src/abis");
const bytecodeDir = join(root, "packages/contracts/src/bytecode");

const contracts = [
  ["ZapDepositor.sol", "ZapDepositor"],
  ["VotingEscrow.sol", "VotingEscrow"],
  ["FeeDistributor.sol", "FeeDistributor"],
  ["RevenueRegistry.sol", "RevenueRegistry"],
  ["SystemAccess.sol", "SystemAccess"],
  ["VeVotesAdapter.sol", "VeVotesAdapter"],
  ["PushAdapter.sol", "PushAdapter"],
  ["FeeSplitter.sol", "FeeSplitter"],
  ["PullAdapter.sol", "PullAdapter"],
  ["ZodiacFeeModule.sol", "ZodiacFeeModule"],
  ["Attestor.sol", "Attestor"],
];

/** Contracts whose creation bytecode is exported for wallet `deployContract`. */
const bytecodeContracts = new Set(["FeeSplitter", "PushAdapter"]);

mkdirSync(abiDir, { recursive: true });
mkdirSync(bytecodeDir, { recursive: true });

const names = [];
const bytecodeNames = [];

for (const [file, name] of contracts) {
  const path = join(outDir, file, `${name}.json`);
  if (!existsSync(path)) {
    console.warn(`skip missing ${path}`);
    continue;
  }
  const artifact = JSON.parse(readFileSync(path, "utf8"));
  const abi = artifact.abi;
  writeFileSync(join(abiDir, `${name}.json`), JSON.stringify(abi, null, 2) + "\n");
  writeFileSync(
    join(abiDir, `${name}.ts`),
    `/* auto-generated by extract-abis.mjs — do not edit */\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  names.push(name);
  console.log(`wrote ${name}.ts (${abi.length} entries)`);

  if (bytecodeContracts.has(name)) {
    const raw = artifact.bytecode?.object ?? artifact.bytecode;
    if (typeof raw !== "string" || raw.length < 4) {
      console.warn(`skip bytecode for ${name}: missing bytecode.object`);
      continue;
    }
    const bytecode = raw.startsWith("0x") ? raw : `0x${raw}`;
    writeFileSync(
      join(bytecodeDir, `${name}.ts`),
      `/* auto-generated by extract-abis.mjs — do not edit */\nexport const ${name}Bytecode = "${bytecode}" as const;\n`,
    );
    writeFileSync(
      join(bytecodeDir, `${name}.json`),
      JSON.stringify({ bytecode }, null, 2) + "\n",
    );
    bytecodeNames.push(name);
    console.log(`wrote bytecode/${name}.ts (${bytecode.length} chars)`);
  }
}

writeFileSync(
  join(abiDir, "index.ts"),
  `/* auto-generated by extract-abis.mjs — do not edit */
${names.map((n) => `import { ${n}Abi } from "./${n}.js";`).join("\n")}

export const abis = {
${names.map((n) => `  ${n}: ${n}Abi,`).join("\n")}
} as const;

export type ContractName = keyof typeof abis;
${names.map((n) => `export { ${n}Abi };`).join("\n")}
`,
);

writeFileSync(
  join(bytecodeDir, "index.ts"),
  `/* auto-generated by extract-abis.mjs — do not edit */
${bytecodeNames.map((n) => `import { ${n}Bytecode } from "./${n}.js";`).join("\n")}

export const bytecodes = {
${bytecodeNames.map((n) => `  ${n}: ${n}Bytecode,`).join("\n")}
} as const;

export type DeployableContractName = keyof typeof bytecodes;
${bytecodeNames.map((n) => `export { ${n}Bytecode };`).join("\n")}
`,
);

console.log("done");
