#!/usr/bin/env node
/**
 * Copies forge `out/<Contract>.sol/<Contract>.json` ABIs into packages/contracts/src/abis.
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "../../..");
const outDir = join(root, "out");
const abiDir = join(root, "packages/contracts/src/abis");

const contracts = [
  ["ZapDepositor.sol", "ZapDepositor"],
  ["VotingEscrow.sol", "VotingEscrow"],
  ["FeeDistributor.sol", "FeeDistributor"],
  ["RevenueRegistry.sol", "RevenueRegistry"],
  ["SystemAccess.sol", "SystemAccess"],
  ["VeVotesAdapter.sol", "VeVotesAdapter"],
  ["PushAdapter.sol", "PushAdapter"],
  ["FeeSplitter.sol", "FeeSplitter"],
  ["PullAdapter.sol", "PullAdapter"],
  ["ZodiacFeeModule.sol", "ZodiacFeeModule"],
  ["Attestor.sol", "Attestor"],
];

mkdirSync(abiDir, { recursive: true });

const names = [];
for (const [file, name] of contracts) {
  const path = join(outDir, file, `${name}.json`);
  if (!existsSync(path)) {
    console.warn(`skip missing ${path}`);
    continue;
  }
  const artifact = JSON.parse(readFileSync(path, "utf8"));
  const abi = artifact.abi;
  writeFileSync(join(abiDir, `${name}.json`), JSON.stringify(abi, null, 2) + "\n");
  writeFileSync(
    join(abiDir, `${name}.ts`),
    `/* auto-generated by extract-abis.mjs — do not edit */\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
  names.push(name);
  console.log(`wrote ${name}.ts (${abi.length} entries)`);
}

writeFileSync(
  join(abiDir, "index.ts"),
  `/* auto-generated by extract-abis.mjs — do not edit */
${names.map((n) => `import { ${n}Abi } from "./${n}.js";`).join("\n")}

export const abis = {
${names.map((n) => `  ${n}: ${n}Abi,`).join("\n")}
} as const;

export type ContractName = keyof typeof abis;
${names.map((n) => `export { ${n}Abi };`).join("\n")}
`,
);

console.log("done");
