/* auto-generated by extract-abis.mjs — do not edit */
import { ZapDepositorAbi } from "./ZapDepositor.js";
import { VotingEscrowAbi } from "./VotingEscrow.js";
import { FeeDistributorAbi } from "./FeeDistributor.js";
import { RevenueRegistryAbi } from "./RevenueRegistry.js";
import { SystemAccessAbi } from "./SystemAccess.js";
import { VeVotesAdapterAbi } from "./VeVotesAdapter.js";
import { PushAdapterAbi } from "./PushAdapter.js";
import { FeeSplitterAbi } from "./FeeSplitter.js";
import { PullAdapterAbi } from "./PullAdapter.js";
import { ZodiacFeeModuleAbi } from "./ZodiacFeeModule.js";
import { AttestorAbi } from "./Attestor.js";

export const abis = {
  ZapDepositor: ZapDepositorAbi,
  VotingEscrow: VotingEscrowAbi,
  FeeDistributor: FeeDistributorAbi,
  RevenueRegistry: RevenueRegistryAbi,
  SystemAccess: SystemAccessAbi,
  VeVotesAdapter: VeVotesAdapterAbi,
  PushAdapter: PushAdapterAbi,
  FeeSplitter: FeeSplitterAbi,
  PullAdapter: PullAdapterAbi,
  ZodiacFeeModule: ZodiacFeeModuleAbi,
  Attestor: AttestorAbi,
} as const;

export type ContractName = keyof typeof abis;
export { ZapDepositorAbi };
export { VotingEscrowAbi };
export { FeeDistributorAbi };
export { RevenueRegistryAbi };
export { SystemAccessAbi };
export { VeVotesAdapterAbi };
export { PushAdapterAbi };
export { FeeSplitterAbi };
export { PullAdapterAbi };
export { ZodiacFeeModuleAbi };
export { AttestorAbi };
