/* auto-generated by extract-abis.mjs — do not edit */
import { PushAdapterBytecode } from "./PushAdapter.js";
import { FeeSplitterBytecode } from "./FeeSplitter.js";

export const bytecodes = {
  PushAdapter: PushAdapterBytecode,
  FeeSplitter: FeeSplitterBytecode,
} as const;

export type DeployableContractName = keyof typeof bytecodes;
export { PushAdapterBytecode };
export { FeeSplitterBytecode };
